spring:
    redis:
        host: localhost
        port: 6379
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        username: sa
        password:
        url: jdbc:h2:mem:test
    jpa:
        hibernate:
            ddl-auto: create  # (1) 스키마 자동 생성
        show-sql: true      # (2) SQL 쿼리 출력
        properties:
            hibernate:
                format_sql: true  # (3) SQL pretty print
    sql:
        init:
            data-locations: classpath*:db/h2/data.sql
    security:
      oauth2:
        client:
              

logging:
    level:
        org:
            springframework:
                orm:
                    jpa : DEBUG

jwt:
    key: ${JWT_SECRET_KEY}
    access-token-expiration-minutes: 30
    refresh-token-expiration-minutes: 420

cloud:
    aws:
        region:
            static: ap-northeast-2
        stack:
            auto: false

# admin용 계정
mail:
    address:
        admin: admin@gmail.com